### ISSUE TITLE
Broken hyperlink associated with the word "intro" in the Lit Documentation

### ISSUE THREAD

**Issue by Giri-Aayush** [LIT-Protocol/docs#124]
While going through the documentation, I noticed that the hyperlink associated with the word "intro" in the sentence "To start building on Lit, check out the Lit SDK intro" is not working. I believe that link should point to the blue mark in the image which I have attached. If that is the case or if there is some other link. Can you please let me know so that I can fix this ASAP, this could be a potential hindrance for new developers trying to get started with the SDK. I've attached an image below for reference.

![intro button](https://github.com/LIT-Protocol/docs/assets/101140354/6fa992b6-d2c8-4092-8430-565b58f7667c)

**Comment by debbly** [comment]
Will be fixed in this PR: https://github.com/LIT-Protocol/docs/pull/132

In the future, please open up a pr with a fix if you understand what the fix is! we'd love to see more contributors on the docs.
