### ISSUE TITLE
"Broken 'Use Cases' Hyperlink in 'Explore More' Section"

### ISSUE THREAD

**Issue by Giri-Aayush** [LIT-Protocol/docs#125]
In the section titled 'Explore more use cases and projects building with Lit,' I observed that the 'use cases' hyperlink is malfunctioning. Instead of leading to the intended content, it redirects to a 'Page Not Found' error. This could prevent users from exploring potential use cases of Lit, which is crucial for understanding its applications. I've attached an image below for clarity.

I'm genuinely interested in rectifying this issue promptly. If provided with the necessary guidance or resources, I'm ready to contribute and ensure that users have a seamless experience when exploring Lit's capabilities.
![use_cases](https://github.com/LIT-Protocol/docs/assets/101140354/d0b3d999-149a-4b11-b344-3ca2f92cef62)

**Comment by debbly** [comment]
awesome, this is going to get fixed in the next couple days with a docs update. In the future, this links to the existing use cases page and is a link update to that! 

Appreciate this issue, if you're able to resolve this on your own, would love to see a PR for the fix!

**Comment by debbly** [comment]
fixed in this pr: https://github.com/LIT-Protocol/docs/pull/131
