### ISSUE TITLE
Incorrect 'Ecosystem RFPs' Hyperlink Redirects to Archived Page

### ISSUE THREAD

**Issue by Giri-Aayush** [LIT-Protocol/docs#126]
In the section mentioning 'Take a look at our Ecosystem RFPs,' the 'Ecosystem RFPs' hyperlink is currently redirecting users to an 'ARCHIVED AND IS NO LONGER BEING MAINTAINED' page. This could be misleading and prevent developers from accessing the latest ideas and feature requests. The correct link should point to https://github.com/orgs/LIT-Protocol/projects/2/views/1. I've attached an image below for reference.

I'm eager to assist in rectifying this issue to ensure developers are directed to the appropriate resources. With the right guidance, I'm confident we can quickly address this and enhance the user experience.
![RFPs](https://github.com/LIT-Protocol/docs/assets/101140354/73f15e51-f6f6-4e18-9dd8-f94fbb713892)

**Comment by debbly** [comment]
fixed in this pr: https://github.com/LIT-Protocol/docs/pull/131
