### ISSUE TITLE
"Broken 'HTML NFT's' Hyperlink in 'Unlockable NFTs' Section"

### ISSUE THREAD

**Issue by Giri-Aayush** [LIT-Protocol/docs#127]
In the 'Unlockable NFTs' section, I noticed that the 'HTML NFT's' hyperlink is malfunctioning. Upon clicking, it redirects users to a 'Page Not Found' error, potentially hindering their exploration of the topic. I've attached an image below for clarity.

I'm genuinely interested in addressing this issue promptly. If provided with the necessary guidance or resources, I'm ready to contribute and ensure that users can seamlessly access all relevant information about Unlockable NFTs.
![HTML_NFTs](https://github.com/LIT-Protocol/docs/assets/101140354/901edcc4-6cd8-4ad3-82ee-3c72266738a1)

**Comment by debbly** [comment]
fixed in this pr: https://github.com/LIT-Protocol/docs/pull/131
