### ISSUE TITLE
Broken Links in 'Litactions-introduction/feature' Section

### ISSUE THREAD

**Issue by Giri-Aayush** [LIT-Protocol/docs#128]
In the 'Litactions-introduction/feature' section, I've identified that the hyperlinks associated with '**Blockchain Agnostic**' and '**off-chain sources**' are not functioning correctly. Clicking on them leads to a 'Page Not Found' error, which could disrupt users' exploration and understanding of these features. I've attached an image below for reference. 
![LitAction-Agnostics](https://github.com/LIT-Protocol/docs/assets/101140354/935b2817-b0a4-434c-b09e-2a8209b96ca4)

**Comment by debbly** [comment]
fixed in this pr: https://github.com/LIT-Protocol/docs/pull/131
