### ISSUE TITLE
Broken Link @ https://developer.litprotocol.com/v3/sdk/capacity-credits

### ISSUE THREAD

**Issue by zach-is-my-name** [LIT-Protocol/docs#208]
"For more information on Capacity Credits and network rate limiting see **here**." 

No page https://developer.litprotocol.com/concepts/capacity-credits-concept.md

Did it intend to link to here? https://developer.litprotocol.com/v3/concepts/capacity-credits-concept

On a phone so can't PR it

**Comment by Aaryan-R-S** [comment]
Thanks @zach-is-my-name 
Fixed the broken links - https://github.com/LIT-Protocol/docs/pull/221
