### ISSUE TITLE
"Start with encryption" -> Page not found

### ISSUE THREAD

**Issue by murksombra** [LIT-Protocol/docs#43]
Hey there! (sorry if I'm reporting this "problem" in a wrong repo)

I was reading your website and documentation to learn more about the project when I clicked on: 
![Screenshot 2022-12-28 at 7 58 17 PM](https://user-images.githubusercontent.com/6532445/209882806-a395d611-c27b-4676-8cbf-6ac51852b1e6.png)

and retrieve the following result:
![Screenshot 2022-12-28 at 7 59 09 PM](https://user-images.githubusercontent.com/6532445/209882873-5ab9c2d1-3f1e-470e-bf0d-f570c085386c.png)

Hope that helps.
Cheers.

**Comment by debbly** [comment]
Thanks for bringing up! We'll have that fixed in the next pull request for the docs :).
