### ISSUE TITLE
I sighted a typographical error in the "What is Lit" section of the documentation.

### ISSUE THREAD

**Issue by ElizabethOgbee** [LIT-Protocol/docs#97]
![Picture1](https://github.com/LIT-Protocol/docs/assets/97669038/2177f866-d446-4788-a14d-a0e5cb1fcdd0)
Under the What is Lit Protocol Section, Its meant to be "Lit provides developers" instead of "Lit providers developers"

**Comment by debbly** [comment]
Awesome, feel free to open up a PR to include the fix for it!

**Comment by debbly** [comment]
Will be fixed in this pr: https://github.com/LIT-Protocol/docs/pull/132
